spring:
  datasource:
    url: jdbc:postgresql://mypostgres:5432/qianxun
    username: postgres
    password: cms@spring
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    generate-ddl: false
